In [1]:
import torch

In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [3]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [4]:
x[2]

tensor(2)

In [5]:
len(x)

3

In [6]:
x.shape

torch.Size([3])

In [7]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [8]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [9]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [10]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [11]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [12]:
# Hadamard product
A * B


tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [13]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [14]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [15]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [16]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [19]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [20]:
A.sum(axis=[0, 1]) == A.sum()

tensor(True)

In [22]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [23]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

In [24]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [25]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [26]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

In [27]:
A.cumsum(axis=1)

tensor([[ 0.,  1.,  3.],
        [ 3.,  7., 12.]])

In [28]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [29]:
torch.sum(x * y)

tensor(3.)

In [30]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

In [31]:
B = torch.ones(3, 4)
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

In [32]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [33]:
torch.abs(u).sum()

tensor(7.)

In [34]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

In [36]:
torch.ones((4, 9))

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [37]:
# exercises

In [40]:
# 1: pass
# 2: pass
# 3: A + tranpose(A) is always symmetric
# 4: length of tensor of shape (2, 3, 4) is 2
# 5: len(x) is axis 0
# 6: error. 0th dimension of matrix to divide must match
# 8: (3, 4), (2, 4), and (2, 3). the axis that was summed on collapses
# 9: the norm function computes the sqrt of the sum of all the elements squared (l2 norm)
# 10: Yes, memory footprint and speed. (AB)C has complexity O(10 * 16 * 5 * 10 * 5 * 14) while A(BC) has 
# complexity O(16 * 5 * 14 * 10 * 16 * 14). Therefore, (AB)C is faster 
# Intermediate matrix (AB) is 10 x 5
# Intermediate matrix (BC) is 16 x 14
# Therefore, (AB)C is also more memory efficient
# recall (m x n)(n x p) costs m x n x p 
# 11: 
# 12: dimensionality depends on the stack axis

In [43]:
C = torch.zeros(2, 3, 4)
C, len(C)

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 2)

In [44]:
A / A.sum(axis=1)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [45]:
A, A.sum(axis=1)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([ 3., 12.]))

In [50]:
D = torch.ones(2, 1)
A / D

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [55]:
E = torch.ones(2, 3, 4)
E.sum(axis=0).shape, E.sum(axis = 1).shape, E.sum(axis = 2).shape

(torch.Size([3, 4]), torch.Size([2, 4]), torch.Size([2, 3]))

In [56]:
torch.linalg.norm(E)

tensor(4.8990)

In [61]:
A = torch.ones(100, 200)
B = torch.ones(100, 200)
C = torch.ones(100, 200)
stack = torch.cat([A, B, C], dim = 0)

stack.shape

torch.Size([300, 200])