In [2]:
import torch

In [3]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [4]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [5]:
x[2]

tensor(2)

In [6]:
len(x)

3

In [7]:
x.shape

torch.Size([3])

In [8]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [9]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [10]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [11]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [12]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [13]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [14]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [15]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [16]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [17]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [18]:
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [19]:
A.sum(axis=[0, 1]) == A.sum()

tensor(True)

In [20]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [21]:
A.mean(axis = 0), A.sum(axis = 0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

In [22]:
sum_A = A.sum(axis = 1, keepdims = True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [23]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [24]:
A.cumsum(axis = 0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

In [25]:
y = torch.ones(3, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [26]:
torch.sum(x * y)

tensor(3.)

In [27]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

In [28]:
B = torch.ones(3, 4)
torch.mm(A, B), A @ B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

In [29]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [30]:
torch.abs(u).sum()

tensor(7.)

In [31]:
torch.norm(torch.ones(4, 9))

tensor(6.)

Exercises

1. some element $a_{ij}$ will become $a_{ji}$. transposed again yields $a_{ij}$ once again, thus proving $(A^T)^T = A$

2. for some element $a_{ij}$ and $b_{ij}$, they become $a{ji} + b{ji}$ in $A^T + B^T$. on the other hand, the same element in $A + B$ is $a_{ij} + b_{ij}$. transposed, we see that the element in $(A+B)^T$ would be $a_{ji} + b_{ji}$. this proves that $A^T + B^T = (A+B)^T$

3. a symmetric matrix is defined as $A = A^T$.

We take the transpose to get

$(A+A^T)^T = A^T + A$

By the commutative property of matrices, we've proven that $A + A^T$ is always symmetric (this is assuming A is square)

4. len(X) = 2 (takes outermost dim)

5. axis 0

6. runtime error due to mismatch dims

7. if non diagonal, L1 norm. If travel diagonal, L2 norm

8. it collapses the axes it sums across (omit the axis)

9. L2 norm

10. 
if you compute (AB)C, then the intermediate matrix AB has dims 10 x 5. (mem)
the time complexity is O(10 * 16 * 5) and then O(10 * 5 * 14)

if you compute A(BC), then the intermediate matrix BC has dims 16 x 14 (mem)
the time complexity is O(16 * 5 * 24) and O(10 * 16 * 24)

it can be seen that (AB)C has better memory and time complexity than A(BC), even though matmul is associative

11. the tranpose operation should take longer

12. pass

In [32]:
X = torch.zeros(2, 3, 4)
X, len(X)

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 2)

In [33]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [34]:
A / A.sum(axis=1)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [35]:
k = torch.rand(2, 3, 4)
k

tensor([[[0.3552, 0.0444, 0.1514, 0.1884],
         [0.6804, 0.5780, 0.6928, 0.0095],
         [0.3905, 0.2744, 0.6199, 0.8032]],

        [[0.4246, 0.5288, 0.7349, 0.1946],
         [0.3019, 0.2181, 0.2401, 0.5523],
         [0.3449, 0.0883, 0.5540, 0.2235]]])

In [36]:
k.sum(axis = 0)

tensor([[0.7798, 0.5732, 0.8863, 0.3830],
        [0.9823, 0.7961, 0.9328, 0.5618],
        [0.7353, 0.3628, 1.1740, 1.0267]])

In [37]:
k.sum(axis = 1)

tensor([[1.4261, 0.8968, 1.4641, 1.0010],
        [1.0713, 0.8353, 1.5290, 0.9704]])

In [38]:
k.sum(axis = 2)

tensor([[0.7394, 1.9607, 2.0880],
        [1.8829, 1.3124, 1.2107]])

In [39]:
a = torch.ones((2, 3, 2, 3))
a * 2

tensor([[[[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]]],


        [[[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.]]]])

In [40]:
(a*2).norm()

tensor(12.)

In [41]:
A = torch.randn(100, 200)
B = torch.randn(100, 200)
C = torch.randn(100, 200)

T = torch.stack([A, B, C], dim=2)

print(T.shape)

torch.Size([100, 200, 3])


In [42]:
print(torch.allclose(T[:, :, 1], B))

True
