In [1]:
%matplotlib inline
import random
import torch
from torch.distributions.multinomial import Multinomial
from d2l import torch as d2l

In [17]:
num_tosses = 100
heads = sum([random.random() > 0.5 for _ in range(num_tosses)])
tails = num_tosses - heads
print("heads, tails: ", [heads, tails])

heads, tails:  [43, 57]


In [18]:
fair_probs = torch.tensor([0.5, 0.5])
Multinomial(100, fair_probs).sample()

tensor([55., 45.])

In [16]:
Multinomial(100, fair_probs).sample() / 100

tensor([0.4900, 0.5100])

In [5]:
counts = Multinomial(10000, fair_probs).sample()
counts / 10000

tensor([0.4937, 0.5063])

In [6]:
# exercises